### ISSUE TITLE
Fix import error (null texture name?)

### ISSUE THREAD

**Issue by andyp123** [andyp123/blender_io_mesh_bsp#18]
This error occurs when importing MODELS of an in development map, which possibly had some faces with no texture on them. A simple check should probably fix this.

Traceback (most recent call last):
  File "C:\Users\Andy\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_mesh_bsp\bsp_importer.py", line 637, in import_bsp
    material_id = material_names.index(texture_name)
ValueError: '' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Andy\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_mesh_bsp\__init__.py", line 126, in execute
    bsp_importer.import_bsp(context, self.filepath, options)
  File "C:\Users\Andy\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\io_mesh_bsp\bsp_importer.py", line 639, in import_bsp
    obj.data.materials.append(bpy.data.materials[texture_name])
KeyError: 'bpy_prop_collection[key]: key "" not found'

location: <unknown location>:-1

**Comment by andyp123** [comment]
Fixed in 1.15
